In [34]:
from sklearn import svm
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import pandas as pd
import numpy as np
data=pd.read_csv('B2_heart.csv')
print(data)
x=data.drop("target",axis=1)
y=data["target"]
print(x,y)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2     

In [35]:

X=np.array([[3,4],[1,4],[2,3],[6,-1],[7,-1],[5,-3]])
Y=np.array([-1,-1,-1,1,1,1])
l=SVC(C=1e5,kernel='linear')
l.fit(X,Y)
print('w=',l.coef_)
print('b=',l.intercept_)
print('indices of support vectors',l.support_)
print('support vectors',l.support_vectors_)
print('no.of support vectors from each class',l.n_support_)
print('coeff of support vectors in  decision function',np.abs(l.dual_coef_))

w= [[ 0.25 -0.25]]
b= [-0.75]
indices of support vectors [2 3]
support vectors [[ 2.  3.]
 [ 6. -1.]]
no.of support vectors from each class [1 1]
coeff of support vectors in  decision function [[0.0625 0.0625]]


In [36]:

linear=svm.SVC(kernel="linear")
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.1)
linear.fit(X_train,Y_train)
y_pred=linear.predict(X_test)
print(linear.support_vectors_)
print(linear.n_support_)

print("accuracy",accuracy_score(Y_test,y_pred))
print("confusion matrix",confusion_matrix(Y_test,y_pred))
print("classification_report")
print(classification_report(Y_test,y_pred))

model1=SVC(kernel='sigmoid')
model1.fit(X_train,Y_train)
y_pred1=model1.predict(X_test)

model2=SVC(kernel='poly')
model2.fit(X_train,Y_train)
y_pred2=model2.predict(X_test)

model3=SVC(kernel='rbf')
model3.fit(X_train,Y_train)
y_pred3=model3.predict(X_test)

print("prediction by model1",accuracy_score(Y_test,y_pred1))
print("prediction by model2",accuracy_score(Y_test,y_pred2))
print("prediction by model3",accuracy_score(Y_test,y_pred3))


[[58.  1.  2. ...  1.  1.  3.]
 [59.  0.  0. ...  1.  0.  2.]
 [44.  1.  0. ...  0.  0.  1.]
 ...
 [65.  1.  0. ...  2.  0.  3.]
 [58.  1.  1. ...  1.  4.  3.]
 [56.  1.  1. ...  2.  0.  3.]]
[51 55]
accuracy 0.7741935483870968
confusion matrix [[ 8  5]
 [ 2 16]]
classification_report
              precision    recall  f1-score   support

           0       0.80      0.62      0.70        13
           1       0.76      0.89      0.82        18

    accuracy                           0.77        31
   macro avg       0.78      0.75      0.76        31
weighted avg       0.78      0.77      0.77        31

prediction by model1 0.5806451612903226
prediction by model2 0.6129032258064516
prediction by model3 0.6451612903225806
